variables:
- group: Credentials

jobs:
- job: Stage
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - bash: |
      cd endomondo_app
      pip3 install -r requirements.txt
      python3 manage.py test
    displayName: 'Tests'
    env:
      ENDOMONDO_USER_PASSWORD: $(ENDOMONDO_USER_PASSWORD)
